### ISSUE TITLE
Allow personalization of SDDI CKAN via config variables

### ISSUE THREAD

**Issue by BWibo** [tum-gis/ckan-docker#23]
### Feature description

Currently, on a few settings, e.g. the [about text](https://docs.ckan.org/en/2.9/maintaining/configuration.html#ckan-site-about) are expose via configuration variables. 

Other important customizations are not accessible via variables, e.g.:
- Default groups and organizations
- Background image (see below)
- Text below intro text (see below)

![grafik](https://github.com/tum-gis/ckan-docker/assets/7643434/e32caa00-abac-437e-a226-b1455f6ab263)

### Suggested solution

Expose these options as config variables. This has to be done in the [ckanext-grouphierarchy-sddi](https://github.com/tum-gis/ckanext-grouphierarchy-sddi):

- Default groups and organizations: Path to `groups_orga.json`. This might require to have separate files for main categories + topics and organizations, hence two different config parameters. The default value should point to the SDDI default config files.
  - It should be possible to specify the config files path as a) URL to an external file somewhere on the web, b) as file path inside the ckan container. The file needs to be structured like [this](https://github.com/tum-gis/ckanext-grouphierarchy-sddi/blob/main/ckanext/grouphierarchy/init_data.json).
  - Is a similar mechanism possible for the icons of groups, topics usw.?
- Background image (see below): Path to `background.jpg`
- Text below intro text (see below): Text to be show.

### Upstream tasks

- [x] https://github.com/tum-gis/ckanext-grouphierarchy-sddi/issues/8

**Comment by BWibo** [comment]
Currently, blocked by upstream issue: tum-gis/ckanext-grouphierarchy-sddi#8

**Comment by MarijaKnezevic** [comment]
This is part of [ckanext-grouphierarchy-sddi](https://github.com/tum-gis/ckanext-grouphierarchy-sddi). Check the issue [#8](https://github.com/tum-gis/ckanext-grouphierarchy-sddi/issues/8)
