### ISSUE TITLE
Current used Basemap is not going to be avaliable from 31. October

### ISSUE THREAD

**Issue by MarijaKnezevic** [tum-gis/ckan-docker#47]
### Feature description

Currently used basemap ([Stamen Terrain](https://docs.ckan.org/projects/ckanext-spatial/en/latest/map-widgets.html#stamen-terrain)) is not going to be avaliable from 31. October 2023 (see attached image).

![stamen-support](https://github.com/tum-gis/ckan-docker/assets/93824048/59fc0231-1b56-480b-bb0b-2b515b0316e6)

### Suggested solution

It should be used other basemap which is supported. Possible configuration could be found [here](https://docs.ckan.org/projects/ckanext-spatial/en/latest/map-widgets.html#common-base-layers-for-map-widgets).

**Comment by MarijaKnezevic** [comment]
It is an upstream issue:
 - posted [here](https://github.com/ckan/ckanext-spatial/issues/317)

**Comment by MarijaKnezevic** [comment]
The issue is solved [here](https://github.com/tum-gis/ckan-docker/blob/2.0.0/sddi-base/Dockerfile#L219-L221)

**Comment by BWibo** [comment]
Fixed in #50
