### ISSUE TITLE
Expanding the Dataset Spatial Extend preview

### ISSUE THREAD

**Issue by MarijaKnezevic** [tum-gis/ckan-docker#52]
### Feature description

In the current version, the _Spatial Dataset extent_ preview is part of the _Additional Info_ table.
The whole potential of the preview is not used and it is required to move the _Spatial Dataset extent_ preview as separate section (as marked in the following image):
![1](https://github.com/tum-gis/ckan-docker/assets/93824048/bc9aebba-7625-4770-80a0-fefa58673632)
On the left side of the image with red color is marked position of  _Spatial Dataset extent_ preview as part of _Additional Info_ table. On the right side of the image with green is marked position of  _Spatial Dataset extent_ preview right as separate section after _Data and Resources_ section.

**Comment by BWibo** [comment]
Fixed in #53
